name: json_store
description: A Flutter storage solution somewhat similar to a browser's localStorage (but super powered)
version: 1.4.0
homepage: https://github.com/fstof/flutter_json_store

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^4.1.0
  flutter_secure_storage: ^3.3.5
  path_provider: ^1.6.27
  sqflite: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
