name: json_store
description: A Flutter storage solution somewhat similar to a browser's localStorage (but super powered)
version: 2.0.0-nullsafety.0
homepage: https://github.com/fstof/flutter_json_store

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.0
  flutter_secure_storage: ^4.2.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
